stages:
  - test
  - build

variables:
  APPLICATION_NAME: api-proxy
  CONTAINER_TAG: ${CI_COMMIT_TAG}
  CONTAINER_IMAGE: ${DOCKER_HUB_USERNAME}/${APPLICATION_NAME}
  CONTAINER_IMAGE_TAGGED: ${CONTAINER_IMAGE}:${CONTAINER_TAG}
  CONTAINER_IMAGE_AARCH64: ${CONTAINER_IMAGE}:aarch64
  CONTAINER_IMAGE_AARCH64_TAGGED: ${CONTAINER_IMAGE}:aarch64-${CONTAINER_TAG}

  # Example URL for TDD in CICD
  PROXY_TEST_VALID: http://localhost
  PROXY_TEST_INVALID: http://localhost:4000

image: moreillon/ci-dind
services:
  - name: docker:24.0.7-dind

test:
  stage: test
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  image: node:20
  tags:
    - dind
  only:
    - tags
  script:
    - npm install
    - npm run coverage

build-x86:
  stage: build
  tags:
    - dind
  only:
    - tags
  before_script:
    - echo "${DOCKER_HUB_PASSWORD}" | docker login --username ${DOCKER_HUB_USERNAME} --password-stdin;
  script:
    - docker build -t ${CONTAINER_IMAGE} .
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE_TAGGED}
    - docker push ${CONTAINER_IMAGE}
    - docker push ${CONTAINER_IMAGE_TAGGED}
# build-aarch64:
#   stage: build
#   tags:
#     - dind
#   only:
#     - tags
#   before_script:
#     - echo "${DOCKER_HUB_PASSWORD}" | docker login --username ${DOCKER_HUB_USERNAME} --password-stdin;
#   script:
#     - docker build -t ${CONTAINER_IMAGE_AARCH64} --platform linux/arm64/v8 .
#     - docker tag ${CONTAINER_IMAGE_AARCH64} ${CONTAINER_IMAGE_AARCH64_TAGGED}
#     - docker push ${CONTAINER_IMAGE_AARCH64}
#     - docker push ${CONTAINER_IMAGE_AARCH64_TAGGED}
